### ISSUE TITLE
get_dir_current isn't set

### ISSUE THREAD

**Issue by tonitch** [TiagoDanin/FileXShared#3]
https://github.com/TiagoDanin/FileXShared/blob/bdaf8ed31b24525e1139e20009373644bd608da0/FileXShared#L87

the var get_dir_current is'nt set anywhere and it create a bug!

![2018-12-27-021828_754x336_scrot](https://user-images.githubusercontent.com/26271060/50461285-b55f6280-097d-11e9-8423-4a3f3247b15f.png)

dunno what was expected here ?

**Comment by TiagoDanin** [comment]
I'm aware of the problem.
Use the version 1.0: [Commits 1.0](https://github.com/TiagoDanin/FileXShared/releases/tag/V0.1) - [Pypi](https://pypi.org/project/FileXShared/)
Version 2.0: Branch Master
Currently this project is archived.

**Comment by tonitch** [comment]
ok no prob. but you maybe should remove it from code triage ?
https://www.codetriage.com/tiagodanin/filexshared

**Comment by TiagoDanin** [comment]
I have no account in CodeTriage.
Done! Version 2.x (Use `npm install filexshared --global`)
![image](https://user-images.githubusercontent.com/5731176/50526364-4b9ba180-0ac0-11e9-8d39-603cff6578dc.png)
